engine:
  type: "in_memory"
network:
  host: "127.0.0.1"
  port: 6969
  max_connections: 100
  max_message_size: "4KB"
  idle_timeout: 5m
logging:
  level: "info"
  output_dir: "logs"
wal:  
  flushing:
    batch_size: 100
    batch_timeout: "10ms"
  max_segment_size: "10MB"
  data_directory: "/data/kdb/wal"
